# Generated by Django 4.1.3 on 2022-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_team_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='media')),
                ('nomi', models.CharField(max_length=40)),
                ('matn', models.CharField(max_length=100)),
                ('vaqt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='vaqt',
            field=models.DateField(auto_now=True),
        ),
    ]
