# Generated by Django 4.1.3 on 2022-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_service_team_vaqt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='matn',
            new_name='matni',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vaqt',
        ),
        migrations.RemoveField(
            model_name='team',
            name='vaqt',
        ),
    ]
